import Head from "next/head";

import { gql, useQuery } from "@apollo/client";
import client from "@/graphql/graphql";

export default function Home() {
const {data, loading, error} = useQuery(gql`
query{
	stats{
_id
 added
country
 end_year
impact
insight
intensity
likelihood
pestle
published
region
relevance
sector
source
start_year
title
topic
url
}
}
`)
console.log(data);
if (error) {
	console.error(error);
	
}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}

export async function getStaticProps() {
	const {data} = await client.query({query: gql`query {
		stats{
		  _id
			        added
			        country
			        end_year
			        impact
			        insight
			        intensity
			        likelihood
			        pestle
			        published
			        region
			        relevance
			        sector
			        source
			        start_year
			        title
			        topic
			        url
		}
	        }
	        `})
console.log(data);

	        return {
	props: {
	stats: data.stats 
	}
	}
}